# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore StoatBog.sln
    - name: Build
      run: dotnet build --no-restore StoatBog.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal StoatBog.sln
    - name: Publish
      run: dotnet publish -r win-x64 -f net9.0 --self-contained true -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -o publish/win-x64 "StoatBog.Desktop/StoatBog.Desktop.csproj"
    - name: Rename Executable
      run: ren "publish/win-x64/StoatBog.Desktop.exe" "StoatBog.exe"
    - name: Inno Setup Action
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
      with:
        path:  StoatBogInstaller.iss
    - name: Get next version
      uses: reecetech/version-increment@2024.10.1
      id: version
      with:
        scheme: semver
        increment: patch
        release_branch: main
    - name: Print Version Number
      run: echo ${{steps.version.outputs.version}}
        
